### ISSUE TITLE
1.6 Beta Feedback

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#350] opened 2023-09-04 07:40 UTC
I have tested on the 20 or so specs in my GitHub and the UI is smooth as butter. All specs work as expected apart from the points below. Overall, it looks great and seems faster to me. My first two points are UI related and a bit subjective so feel free to ignore and close those.

1. This button bar feels a little "off". The first three are tabs and the second three are buttons but with the first four having text, it feels like they're logically related. Maybe make the Apply Changes button an icon or come up with more obvious difference between button and tab functionality. I'll get used to it but it was not completely intuitive at first glance. 
![image](https://github.com/deneb-viz/deneb/assets/86846675/02345b62-3b5f-49ca-862c-cadb73ec7a63)

2. The tables have a **lot** of padding in there. Obviously, padding makes them look nice but I prefer information density when developing with these tables and try and pack as much on screen as possible. 
![image](https://github.com/deneb-viz/deneb/assets/86846675/327785fc-6d16-4f49-a46a-8a55e757ae3f)

![image](https://github.com/deneb-viz/deneb/assets/86846675/784ee828-cce2-49c0-bc35-620f602d86d5)

3. S&P Bubble Chart (https://github.com/PBI-David/Deneb-Showcase/tree/main/S%26P%20Beeswarm%20Chart) loads a lot more slowly. V1.5 loads in about 15 seconds where as 1.6 loads in about 30 seconds.

4.  Covid Map (https://github.com/PBI-David/Deneb-Showcase/tree/main/Covid%20Map) doesn't load all the data but I can't remember if this was always the case as the same behaviour can be observed in 1.5 too. This is probably not a regression as this spec was always a hack to get working in Deneb. 

It looks great and I can't imagine the huge amount of work you've had to do to get to this stage. 🏆

**Comment by dm-p** [comment] 2023-09-04 23:17
Thanks for the fast feedback, @PBI-David! I really appreciate you putting your visuals through the paces. You can see how much it took to get here by looking at the [initial PR](https://github.com/deneb-viz/deneb/pull/349) (if you dare) ;)

Regarding feedback items:

1. I'll have a think about the button - I was hoping to be more condensed and similar to Vega Editor, but they have the tabs underneath the menu, which probably breaks things up. Ultimately the previous approach of having 2 separate icons is probably as economical. We could either add labels to the other buttons (but this might have issues with narrower screens due to increased space but fall back to icons in these cases) or move back to the previous UX of having a dedicated icon button for each mode and disabling as applicable?

2. I can't do much about the horizontal padding, as we need the space reserving for the sort icon on each column, but I can change the row height to be more condensed (from 32px to 24px). Would this look better for you?
![image](https://github.com/deneb-viz/deneb/assets/10572054/4e1dc3ef-8c89-43bd-855f-dcdb8708cc98)
![image](https://github.com/deneb-viz/deneb/assets/10572054/02d6ec52-8c56-428f-b4a1-d123075b413d)

3. I'll have to check this one out to see if there's anything specific to the spec that is causing the slowdown.

4. We haven't seen any significant changes to data processing since 1.2 (when cross-highlight values were added). We have extended this in 1.6 with the formatting strings for measures, but if it's like this in 1.5 then I would agree that this isn't a regression. Would suggest that if you feel it's incorrect, then we can create a separate issue to track it.

**Comment by PBI-David** [comment] 2023-09-05 07:55
Thanks Daniel - that PR is huge 😮.

Regarding the points:

1. I definitely like the idea of icons.
2. Yes, that row height is much better! That gets my vote. 
3. Understood. The spec is loading large amounts of data and then using a timer to cycle through it all. I think any spec with large amounts of data would be an equivalent test. 
4. Agreed, not a regression. The spec was always a hack and we probably need supported ways to get geojson files into Deneb. Have you thought any more about this?

Thanks for all your hard work!

**Comment by dm-p** [comment] 2023-09-05 23:02
The library offers a toggle button, but it's literally that. It's kind of like a checkbox. The requirements we have on apply vs. auto apply (and state management) make this tricky to fit in with the framework, which TBH probably means that it's the wrong approach.

The new alpha build has the revised table changes, and I've reverted the toolbar behavior to how it was previously, e.g.:

- User applying changes manually:

  ![image](https://github.com/deneb-viz/deneb/assets/10572054/9e8842fa-5247-4011-979d-e6183068f4e1)

- User has toggled auto-apply:
  
  ![image](https://github.com/deneb-viz/deneb/assets/10572054/4433c502-797b-4030-93c7-4903b61943d4)

If you're able to have another look and confirm how this works for you, that would be very helpful :)

Regarding point 3, I'll raise a separate issue for it so we can track it there. Given that 19/20 (I assume) of your cases are improved, would you be happy for this to wait until 1.7? I'm just trying to ascertain risk at this stage of development and testing.

**Comment by PBI-David** [comment] 2023-09-06 06:58
Thanks. The new buttons and row height looks much better to me and is much more useable. 

Happy for point 3 to be tracked separately as all the other specs work fine. 

I have identified a bad crash though which I will post another issue for so you can close this one down.

**Comment by dm-p** [comment] 2023-09-07 23:34
I've had a chance to look at the S&P example, and this takes ~30 seconds to open for me when using 1.5, vs. ~18 seconds on 1.6. Admittedly, this is the latest alpha build from #352, so it could be worth taking another look at that one also, i fyou have the opportunity.

**Comment by PBI-David** [comment] 2023-09-08 09:27
I still see the opposite which is strange. To be crystal clear, I am opening the report, clicking the Deneb visual and clicking either the certified 1.5 or alpha 1.6 and then starting a timer. 1.5 loads in about 12 seconds and 1.6 takes at least double that. I'm on a powerful desktop but that would make no relative difference. It varies each time but is usually double. 

In fact, on two occasions that I switched to alpha build, I got a full PBI crash (I had switched back and forth a few times for testing but waited for the render to finish each time).

![image](https://github.com/deneb-viz/deneb/assets/86846675/c521cb26-a8c8-4b86-8b71-df9211b41d47)


![image](https://github.com/deneb-viz/deneb/assets/86846675/7b69bd75-0a05-4d58-87cc-9d9ad4996d86)

**Comment by dm-p** [comment] 2023-09-10 03:31
Ok, thanks for clarifying. This is not what I was attempting in my analysis, and I now see what you mean.

I'll create a separate issue for this, but it will likely be related to one of the following changes in 1.6:

1. We now include the entire dataset when the spec is parsed rather than just the spec. react-vega wasn't including the data until after the view was created, and this was causing a lot of the errors we couldn't easily identify (e.g., #233, #289, #293). The downside of this might be the performance hit with including such a large dataset.
2. Auto-creation of format string support fields for measures (which adds overhead to the dataset processing), but I don't see this happening in your visual due to the dataset being comprised of columns. I was due to take a look at this in 1.6 (#339), and I might move this up to 1.7 either way.

As the other points are resolved, I'll close this and the new issue will take over for tracking the S&P performance/crash.

**Closed by dm-p** 2023-09-10 03:31 UTC
