### ISSUE TITLE
Power BI freeze

### ISSUE THREAD

**Issue by anten-puzl** [deneb-viz/deneb#525] opened 2024-12-28 00:01 UTC
The visualization uses an arch. In order for the visualization to resize when the container is changed, I added coefficients to recalculate the dimensions.Now, when changing the size of the visualization, Power Bi is freezed. To reproduce the problem, open the report, highlight the visualization, and quickly move it around the corner. Your Power BI will freeze.
https://drive.google.com/file/d/1JiQwrhxUdBNT6QCSq-8t-rowhbWScZJY/view?usp=sharing

**Comment by dm-p** [comment] 2024-12-31 01:31
Hi, and thanks for raising. Sorry that this is causing you issues. 

This is a duplicate of #514. You can mitigate by modifying your config to the following, rather than what you currently have:

````json
{
  "autosize": {
    "type": "fit",
    "contains": "padding"
  }
}
````

So, basically:

* Remove the `height` and `width` properties (Deneb will patch these for you if absent).
* Remove the `resize: true` configuration (Deneb will recalculate the view on resize anyway).

For some reason, these are causing a problem in the back end, which I have not yet had a chance to investigate thoroughly. Hopefully, I'll get a chance when I'm back after the Holidays and issue an update soon, but for now, this is the workaround you should use.

Here's a short video of me doing this. After applying the changes, you should notice that the visual no longer freezes Power BI.

https://github.com/user-attachments/assets/afdcfb40-ca85-444b-ae1f-79cd0e76f1c9

As we're already tracking this in #514, I'll close this issue down. I suggest you keep an eye on that one for activity and possibly assist with testing any potential fixes if you are keen to help. I'll use your repro as a way of validation from my end, though. Thanks again for helping make Deneb as stable and reliable as possible 🙏

**Closed by dm-p** 2024-12-31 01:31 UTC
Labels: bug, duplicate

**Comment by anten-puzl** [comment] 2025-01-05 15:01
thank you! it helped
