### ISSUE TITLE
v1.7: comma separator not working in tooltip

### ISSUE THREAD

**Issue by vfridkin** [deneb-viz/deneb#483] opened 2024-07-31 06:20 UTC
Previous this used to give values in a tooltip, formatted with commas separating each power of 1000:

```
                "format": ",#0",
                "formatType": "pbiFormat",
```

So 1000000 would be formatted 1,000,000.

In 1.7.0.0 it returns 'False' instead of a value in the tooltip.

Tested for text and bar tooltips.

**Comment by vfridkin** [comment] 2024-07-31 06:38
Removing the comma returns the value, however it is not comma separated.  I've tried to use the D3 formatting and that also doesn't seem to work in the tooltip.

**Comment by dm-p** [comment] 2024-07-31 21:54
Hi, and thanks for raising the issue. It looks like we might have a regression against #429. I will have a look as soon as I can.

For the moment, you can disable the tooltip handler:

![image](https://github.com/user-attachments/assets/717155bf-5ff8-4352-a169-aad08aebe963)

This will use the Vega tooltip handler, and `pbiFormat` will work as intended in here, e.g.:

![image](https://github.com/user-attachments/assets/0969cb89-f455-43b5-8cd1-801a400ea541)

**Comment by dm-p** [comment] 2024-07-31 22:25
A workaround that will work with the Power BI tooltip: add a `title` to the encoding channel that differs from the base field name, even if it has a trailing space, e.g.:

```json
{
  ...
  "encoding": {
    ...
    "tooltip": [
      ...
      {
        "field": "$ Sales",
        "title": "$ Sales ",
        "format": ",#0",
        "formatType": "pbiFormat"
      }
    ]
  }
}
```
![image](https://github.com/user-attachments/assets/c87aec74-5f00-4177-b003-d3beff19203a)

Without `title` (or `title` commented out):

![image](https://github.com/user-attachments/assets/f53eff4f-e0d0-4de8-8364-665513c37656)

**Comment by dm-p** [comment] 2024-07-31 23:06
I've isolated the root cause and have what I believe is a resilient fix. I would appreciate it if anyone affected could re-test with this (plus any other use cases they can think of) to ensure this is resolved.

When ready to submit, **it takes 2-3 weeks for certification and up to 2 further weeks to be delivered to all reports by MS**, so this needs to be correct. To test:

* Download the file
* Remove the .zip extension (so it is now a valid .pbiviz)
* Load into your workbook and convert your affected visual over to this alpha version
* Confirm tooltip functionality is as expected

If you encounter any further issues, please provide reproducible examples, as OP has done. Your efforts in this regard are greatly appreciated and significantly speed up the isolation and fixing process. Thank you for your continued support 🙏 

File: [deneb-alpha.1.7.1.20240731#60f5bc4.pbiviz.zip](https://github.com/user-attachments/files/16447919/deneb-alpha.1.7.1.20240731.60f5bc4.pbiviz.zip)

> The usual disclaimers apply about downloading visuals from unsolicited sources. I attest that while this alpha build uses a different GUID and is therefore regarded as uncertified by Power BI, it is built with the certified visual permissions (no external comms) and confirms to [Deneb's privacy policy](https://deneb-viz.github.io/privacy-policy) **If downloaded directly from this above link**.

**Comment by vfridkin** [comment] 2024-08-01 22:29
I can confirm this version works after following your instructions.  I've tested it for four cases where the formatting failed and in all cases this version meets expected functionality.

**Comment by dm-p** [comment] 2024-08-01 23:03
Thanks so much for confirming! I'm just trying to fix another couple of minor issues, and then I will submit it to MS. 

For your information, the CI process will close this ticket when I merge the changes to the main branch, but I'll advise when the standalone version is available (as I make this available ahead of the MS timeline), you could probably use either workaround above in the meantime if you are dependent on the certified version.

**Closed** 2024-08-01 23:11 UTC
Labels: bug

**Comment by remsidave** [comment] 2024-08-05 15:05
> I've isolated the root cause and have what I believe is a resilient fix. I would appreciate it if anyone affected could re-test with this (plus any other use cases they can think of) to ensure this is resolved.
> 
> When ready to submit, **it takes 2-3 weeks for certification and up to 2 further weeks to be delivered to all reports by MS**, so this needs to be correct. To test:
> 
> * Download the file
> * Remove the .zip extension (so it is now a valid .pbiviz)
> * Load into your workbook and convert your affected visual over to this alpha version
> * Confirm tooltip functionality is as expected
> 
> If you encounter any further issues, please provide reproducible examples, as OP has done. Your efforts in this regard are greatly appreciated and significantly speed up the isolation and fixing process. Thank you for your continued support 🙏
> 
> File: [deneb-alpha.1.7.1.20240731#60f5bc4.pbiviz.zip](https://github.com/user-attachments/files/16447919/deneb-alpha.1.7.1.20240731.60f5bc4.pbiviz.zip)
> 
> > The usual disclaimers apply about downloading visuals from unsolicited sources. I attest that while this alpha build uses a different GUID and is therefore regarded as uncertified by Power BI, it is built with certified visual permissions (no external comms). It conforms to [Deneb's privacy policy](https://deneb-viz.github.io/privacy-policy) **If downloaded directly from this above link**.

I can also confirm that the tooltip works again as excepted with the alpha build
