### ISSUE TITLE
Issue with Reloading Templates in Deneb

### ISSUE THREAD

**Issue by CSalcedoDataBI** [deneb-viz/deneb#445] opened 2024-05-21 15:23 UTC
---

**Issue with Reloading Templates in Deneb**

When working with templates in Deneb, I sometimes make adjustments in Visual Studio Code within the template or do not correctly place the variables when using the template. As a result, I need to retrieve the template again. In either case, if I try to reload the template, it does not work. It does not allow me to recreate it from the template. I have to exit the Deneb editor, navigate away from the Power BI page, and then return. Only then does it work. 

I have noticed this issue in the latest version of Deneb. Initially, I thought it was due to the complex logic in my VEGA templates, but I didn't have time to test this. Recently, I had some time and tested it with the default bar chart template provided by Deneb, and the behavior is similar. 

I want to highlight that this issue did not occur in previous versions of Deneb. You can see this behavior in the attached image.gif.

---
![XRAgriqexC20240521-094620 Example](https://github.com/deneb-viz/deneb-viz.github.io/assets/73630372/cefe5b2e-f409-4639-94ee-dd134c14710e)

**Comment by dm-p** [comment] 2024-05-21 22:25
[Transferred from doc site repo to Deneb repo]

I suspect this is a state issue in the dialog. Having to exit the editor, page etc. might be a bit extreme. 

Can you confirm if changing the provider (e.g., going to Vega/Vega-Lite in the dialog and then switching back to import) mitigates the problem? It should update the currently staged template with a new one. You should then be able to return to the import option and re-import your template.

**Comment by CSalcedoDataBI** [comment] 2024-05-21 23:00
Wow, Daniel! Thank you very much for your prompt response. I really didn't know this trick and was taking a long and tedious path. I tried what you suggested and it worked perfectly. Thank you so much!

**Comment by dm-p** [comment] 2024-05-21 23:03
Glad to know the workaround saves you a bit of time. The underlying issue is still a bug though and I will look at fixing it.

I'm just in the final stages of stabilization for 1.7 before opening up beta testing. If this is quick to solve, I'll try to squeeze it in; otherwise, I'll schedule for 1.8.

**Comment by dm-p** [comment] 2024-05-22 01:37
@CSalcedoDataBI : I have reproduced it in 1.6 as per your steps and attempted to reproduce it in 1.7, and it might have already been resolved due to some other changes made in this part of the application for JSONC support. Can you please re-test with the [latest alpha build](https://github.com/deneb-viz/deneb/releases/tag/alpha) and confirm your issue if no longer happening?

**Comment by CSalcedoDataBI** [comment] 2024-05-22 03:12
@dm-p I’ve tested this in version 1.7, and everything works perfectly. Many thanks!

**Closed** 2024-05-22 03:13 UTC
Labels: bug

**Comment by CSalcedoDataBI** [comment] 2024-05-29 21:01
Feedback and Suggestion on Deneb Version 1.7.0.20240522#3a93f7d

Hello @dm-p,

I hope this message finds you well. I wanted to share my experience with the Deneb version 1.7.0.20240522#3a93f7d that we discussed in our last conversation.

I have been alternating between the official version 1.6 and the 1.7.0.20240522#3a93f7d while developing visualizations that range from 2000 to 4000 lines of code. There are several aspects of the new version that I really like, such as the improved formatting, the dark and light mode options in the interface, the additional space for signal names, and the helpful suggestions that appear as I write code.

However, I have noticed that the performance in this version is quite slow, experiencing delays of several seconds while writing or applying changes to the code. Additionally, it would be extremely beneficial if tooltips could be implemented for the content of those signals that contain objects or arrays, which would greatly enhance the understanding and interaction with these complex elements.

I understand that you are working hard on these improvements, and therefore I wanted to share my feedback and this suggestion so that you can take them into account.

I appreciate your efforts greatly and hope this information is useful to you.

Best regards

**Comment by dm-p** [comment] 2024-05-29 21:58
Hi @CSalcedoDataBI, and thanks very much for your feedback. Anything we can catch early is good 🙂

Anything unrelated to the original issue (and particularly if the original issue has been closed) is probably better to create a new issue for it so that it's more visible to other folks who might be experiencing the same problem and looking for an existing thread to add their thoughts to. That being said, I'll provide some feedback here, and you can decide if you need to take any further action.

## Performance

This is a side effect of adding the new features, JSONC particularly. This adds a lot of processing overhead, as the text has to be parsed and sanitized. We also have the following workflow whenever a spec is persisted or remapped:

1. Process the text as JSONC
2. Extract field usage from each node (which requires a visit to each key/property as the JSON is being evaluated and processed)
3. Replace the discovered fields with tokens, so that we can track them for mapping and template export purposes.

As part of the stabilization work for 1.7 before moving/announcing beta testing, I have been working with specifications with > 100,000 lines, and this issue has already been identified and itemized in #434 as something to address. 

I have a strategy for moving this expensive process to another thread, which will do the expensive work asynchronously, hopefully not block the main thread and allow you to continue working. However, this is not a small task, and it will probably be a few weeks before I have something delivered here. But it will be better before 1.7 moves to beta. 

If you're keen to help verify this is moving in the right direction, I'd suggest keeping a watch on the repo for new alpha releases or on #434 to see how these tasks are going. It would certainly be good to know if the improvements I'll be delivering have a beneficial effect on  your work 👍

## Tooltips

If you're referring to the information when you hover over specific JSON language items, this documentation is sourced from the Vega and Vega-Lite language schemas, provided by that team. If there are differences between what happens in Vega Editor and Deneb, I'd be happy to take a look. If this is the case, can you provide a worked example with steps to reproduce in a new issue that I can reproduce and investigate? 

Otherwise, if the behavior is the same in both tools, you will need to make a feature request for either Vega or Vega-Lite as appropriate, or you can contribute the changes to the source code and make a pull request. As soon as a new version of the appropriate language is available, I can integrate it into Deneb, and these changes should propagate through.

**Comment by CSalcedoDataBI** [comment] 2024-05-30 02:22
Thank you, @dm-p, for your timely response. I apologize for not creating the issue as a new one; I'll keep that in mind for next time. I will create a new issue specifically to explain the tooltip matter, as I didn't make myself clear previously
