### ISSUE TITLE
V 1.7 not rendering on Power BI Service

### ISSUE THREAD

**Issue by thetom88** [deneb-viz/deneb#476] opened 2024-07-24 08:49 UTC
Hello deneb community and thank you for your amazing work.
We're facing some issues with version 1.7. essentially visuals are not rendering on the service. 1.6.2 was working fine, now it's been upgraded on the service to 1.7 and visuals are not rendered. I tried downloading the PBIX from the service and visuals are rendered correctly on PBI desktop. I see the JS errors I posted in the attachment when I load a page that has deneb visuals on the service.
If you need more information to debug the issue I'll be glad to provide them.
Thank you for your support 
![Js error](https://github.com/user-attachments/assets/8001df3d-a0bc-4f73-8fa4-b1eb2748e835)

EDIT 15:49. Adding a couple of information. The tenant is using Microsoft Defender for Cloud Apps (MCAS), in the past we've encountered some issues even with legacy visuals. I confirm that if I export the report in the power point slides visuals are rendered correctly.

**Comment by dm-p** [comment] 2024-07-24 22:06
Hi @thetom88, and thanks for reporting. Sorry to hear you're having issues.

1.7 hasn't gone live in my tenant yet, so I can't mimic the AppSource delivery process. Still, I'm having no issues if I manually overwrite the visual with 1.7, which is the best I can do at this time in attempting to reproduce.

If it's working on the Desktop, it suggests that it's a browser issue. The PowerPoint and PDF rendering is done server-side rather than in your local browser session, so this also tracks.

Can you please confirm the following (in order of importance/ability for me to try and zero in on the issue):

* Did you participate in the public beta testing, and did Deneb work as expected when you checked it for your existing visuals?

* Browser and version you're using.

* If you can share the .pbix so I can see the spec in situ (especially if you're using a browser and version I have to support for certified visuals), that would be great. Ideally, this can be reproduced on public data that you can share freely, but, if need be, I can receive this privately and sign an NDA if required.

* If possible, how MCAS is configured in your tenant so I can see if I can replicate this setup.

* If you have other custom visual permissions set at the tenant level.

    ![image](https://github.com/user-attachments/assets/f4d1a35f-1527-4917-b977-740885d305ea)

    The only one Deneb leverages is 'Allow downloads from custom visuals,' so the others shouldn't matter (and even this one isn't a deal-breaker). Still, it could be worth confirming anything different from the defaults.

* Any specific browser extensions you may have enabled. Custom visuals have recently had issues with anti-virus and password manager utilities, which rewrite the iframe in which they are hosted. We often have to pass this on to MS for them to fix. It's hard to test the anti-virus scenario as this requires disabling protection on your system, but it may be possible to test the extensions if they are present:

    * If you have permission, disable such extensions in your browser and reload the report.
    * If you can't disable extensions (and providing that these extensions aren't enabled in incognito mode also), try logging into Power BI in your browser's incognito mode to see if the visual loads.

* Can you use the [standalone version](https://deneb-viz.github.io/getting-started#standalone-version) in your environment? If so, this means we may be able to at least get a build running with some debugging info turned on if nothing from the above bears fruit.

If nothing obvious comes from this, we might have to have a look in situ. Let's see what we can do about the other info first, and I'll investigate any new details as soon as I can.

----

@code4578: Thanks also for contacting me and letting me know you're experiencing problems. This sounds like a different problem than @ thetom88, as MS renders the PDF export server-side. It's probably best we track this separately. I have raised #477 to track this, so if you can follow up there, we can keep the conversations focused on each specific issue without having to track multiple threads.

**Comment by thetom88** [comment] 2024-07-25 12:43
Hello @dm-p , I'm sharing a couple of updates on the tests we've performed. We've manually removed on the tenant the version 1.7.0.0 installed from the store, installed the 1.6.2.1 version on the tenant from file and visuals are rendering correctly. 
We've tried to manually install v 1.7.0.0 from file on the tenant and visuals are not rendering. 
The customer is opening a support ticket to Microsoft now. They're also testing what happens if they disable MCAS.
I'm experiencing some weird behaviors when testing on my work laptop locally on Power BI. If I install v1.7.0.0 from the store I receive version 1.6.2.1. That happens also if I install version 1.7.0.0 from file.
I can share with you the tenant visual configuration:
![pbi visual config](https://github.com/user-attachments/assets/551b4a51-7900-4f46-826a-ff96fa372bb6)
I will ask if it's possible to install on the tenant standalone version and grab console output if it may help you debugging the issue.
I'll keep you updated. Thank you again for your support.

**Comment by dm-p** [comment] 2024-07-25 23:32
Hi @thetom88, and thanks for all the follow-up details. The version of Chrome looks a _little_ old, but not that old that web worker support would be missing. I'll have to think about this a bit more and also see if I can get ahold of this version and replicate things on there.

Regarding 1.6 appearing on your laptop vs what the store is saying: the listing gets updated first to say the new version, but it takes up to two weeks to fully deploy. If 1.6 is being loaded in place, that suggests that the CDN for your tenant hasn't been updated yet. If you manually load the file, Power BI detects that the visual's ID is connected to AppSource and will always load the version from there (it's how it auto-updates visuals). [You can temporarily override this in Desktop by turning on a setting](https://learn.microsoft.com/en-us/power-bi/developer/visuals/submission-testing#enable-developer-mode-in-power-bi-desktop) if you want to try it.

Glad to know that 1.6 is mitigating the issue, and it does suggest that you weren't using any 1.7 features that aren't present in 1.6. For instance, we've discovered that some folks had 1.7 live in Desktop and on their tenant, so were pushing up specs with comments in them, but when PDFs were getting generated, the version MS is using to generate the PDF (which is separate from both) still appears to be on 1.6 for the moment. Removing the comments fixed that issue as a workaround, and we expect this to work when it catches up. I don't think this is the same as your issue, as you're getting very specific errors in the console.

So, nothing firm from my end yet, just confirmation that I've seen your replies and will try to factor them into any investigations.

**Comment by dm-p** [comment] 2024-07-26 02:59
Just a note that I've done the most straightforward test and I downgraded Chrome to 118.0.5993.118. I tested with 1.7 standalone (as 1.7 AppSource isn't live for me yet). It works as expected in the Service (both read and edit modes). There's probably much more to it, but just wanted to check this out of curiosity,

**Comment by thetom88** [comment] 2024-07-30 08:47
Hello @dm-p , just a quick update on my side. We've tried to disable MCAS and the visual is rendered correctly on the service, so I guess we've found the issue. In the past I've encountered problems with MCAS even on native visuals and Microsoft fixed the issue. We've just opened a ticket to Microsoft to investigate our case. I'll let you know how it goes. Thank you very much for your support!

**Comment by dm-p** [comment] 2024-07-30 22:01
Thanks so much for confirming where the root cause lies 👍 

I'll close this for now, but if you ever do find out what the specific issue might be, please feel free to update here or email me - daniel@coacervo.co, as this could be very useful information for anyone else who may experience this (or there may even be something we can do defensively in Deneb if the error fires, so we may be able to direct the user to look at this specifically).

**Closed by dm-p** 2024-07-30 22:01 UTC
Labels: bug
