### ISSUE TITLE
Cannot Open Web Browser

### ISSUE THREAD

**Issue by PBI-David** [deneb-viz/deneb#491] opened 2024-08-08 20:59 UTC
Version 1.7.0.0

I have a weird unicode char in my spec. When I hover over, I get a link which when clicked presents a dialogue saying malformed url. 

Char:  

![image](https://github.com/user-attachments/assets/f7a44d11-090e-4330-a1c1-a4b5b5e933ba)

![image](https://github.com/user-attachments/assets/f82909be-559e-42e4-88cf-da4291686308)

**Comment by dm-p** [comment] 2024-08-11 23:23
I'm having some trouble replicating this one - I've added an invisible Unicode character to a spec, and I get the tooltip, but clicking this triggers the command palette as I might expect:

![image](https://github.com/user-attachments/assets/6f98cf98-231c-4d80-874e-5003f89be6b3)

I can't reproduce in 1.7.0 or 1.7.1, but I did make some changes to make the tooltip link override less shotgun-like for markdown URLs. Can you try this for your situation in 1.7.1? It's been certified and is pending deployment to production, but the standalone build is available as normal.

If this is still not working for you, would it be possible to provide a workbook so I can see if it's something specific to where you're accepting this in your specs? It should be much easier to isolate and diagnose. And if it's a quick fix, I can get into 1.7.2, as I'll be looking to submit this soon.

**Comment by PBI-David** [comment] 2024-08-12 09:17
This is still present in 1.7.1. You have to be quick to click adjust settings in the tooltip when hovering over this

![image](https://github.com/user-attachments/assets/bc9c9e8d-fa1e-4ccd-8648-b06a1c2070dc)
[Daniel.pbix.zip](https://github.com/user-attachments/files/16579665/Daniel.pbix.zip)

**Comment by dm-p** [comment] 2024-08-28 21:52
Ah, the issue only seems to be for Desktop. We develop/debug visuals in the Service, and it seems to work OK there which is why I wasn't able to see it (in that "working OK" is not triggering the protocol error dialog that the Desktop is bringing up). 

Having done some digging, the functionality itself is a [known issue for Monaco](https://github.com/microsoft/monaco-editor/issues/2940) (only supporting VS Code as a host). The suggested workaround listed in that issue is to disable the highlight option, but this has downstream effects on the parsing (due to the invalid characters) potentially being in the whitespace portion. Therefore, the highlight and tooltip are useful for the user to understand where potential issues might be if their spec doesn't parse.

In terms of a way forward, I can fix the dialog box issue by only ensuring that HTTP(s) URLs will trigger the Power BI URL Launch API dialog, and this will now work as expected in Desktop. However, I think that for now we will have to accept that the while the 'Adjust settings' link will then display options in the command palette, they will not do anything. Does this sound reasonable?

**Comment by PBI-David** [comment] 2024-08-29 07:12
Sorry - I should have been clear that this was in desktop. As for the fix, I'll go with whatever you think is best. Thanks

**Comment by dm-p** [comment] 2024-08-29 22:33
Cheers! I've set up as I originally proposed: the Launch URL API will ignore non-HTTP (s) URLs in tooltips and treat them as normal. The Monaco issue with the setting not being applied remains, but at least this should prevent the UI from attempting to navigate to an app protocol-based URL.

I've merged a PR with the current 1.7.2 bug fixes, so a new alpha build should be available if you want to confirm that this works.

All being well, I'm planning to submit 1.7.2 before early/mid next week 🤞

**Comment by dm-p** [comment] 2024-09-04 02:37
1.7.2 has been submitted to AppSource, so this should be live in your reports in a few weeks. For now, the standalone edition is available in the typical manner. [This blog post](https://deneb-viz.github.io/blog/1-7-2-submission) provides links to the change log and info if you'd like to use the standalone version in the meantime.

**Closed by dm-p** 2024-09-04 02:37 UTC
Labels: bug
