### ISSUE TITLE
French flag not displayed correctly

### ISSUE THREAD

**Issue by AUNEZ** [deneb-viz/deneb#356] opened 2023-09-09 16:14 UTC
Hi,

ID : ID: ALPHAdeneb7E15AEF80B9E4D4F8E12924291ECE89A
Version : Version: 1.6.0.20230907#f92a646

In one visual, I displayed top runners having won the most stages in Tour de France. Besides the runner's name, I display the flag. I get all the SVG flags correctly displayed. French flag is stored as a http/JPG address (I got it first, I kept as is, it would not be difficult to upgrade to SVG)  : http://fr.wikimediation.org/images/0/0e/Drapeau_francais.jpg

And this is not displayed any more : the version 1.5 still displays, the alpha build does not. Even though, I want aonly to display the french flag without mixing SVG and http flags.

Fabrice
(I am sure you're a great fan of the mythic All Blacks and the flag will reappear soon when they win the other matches)

**Comment by dm-p** [comment] 2023-09-10 03:11
Hi Fabrice, and thanks for helping to test Deneb! I really appreciate your contribution. There should be no geographic or sports team-related bias with Deneb ;)

The alpha build should have the same permissions as the AppSource (certified) version, and as such if a remote endpoint were blocked (like it is here) then that would be expected behavior. You don't say whether your comparison edition of 1.5 is the standalone version or the AppSource version, but if you're using the standalone edition of 1.5, then this should be able to load from an HTTP endpoint, as we don't restrict the Vega loader in this edition. If you're using the AppSource edition, then this is unintended behavior and would actually be a bug with 1.5 (as certified visuals should not be permitted to load from an HTTP endpoint).

If you have any further details I can investigate a bit more, but based on the info I have, this would be as expected.

**Comment by dm-p** [comment] 2024-06-26 23:01
As there's no further information and this has been open for some time, I'm closing it. If it still needs looking into, please provide details that can help investigate and solve the problem, and we'll take another look.

**Closed by dm-p** 2024-06-26 23:01 UTC
