### ISSUE TITLE
Issue of uncorrect sorting of data in a calendar heatmap in vega lite

### ISSUE THREAD

**Issue by CrabNebula25** [deneb-viz/deneb#516] opened 2024-11-07 09:10 UTC
Hello,

When creating a calendar heatmap, we are finding discrepancies.

We have entered the values of the months to count daily attendance. The problem is that the values are not correctly reported in the order of dates. It seems as if the code moves the graph to the right. For example, in the row Sala2 for the month of January, the data of September of Sala1 are displayed.
![Vega lite](https://github.com/user-attachments/assets/c110a308-6e4a-4f02-b508-d9a6ae50d2e6)

Can you help us understand the problem?

In the attachments you can find the code of the chart
[vega lite code.txt](https://github.com/user-attachments/files/17658974/vega.lite.code.txt)

Thanky you!

Best,
Luca

**Comment by CSalcedoDataBI** [comment] 2024-12-06 18:45
It’s possible that the issue is related to how the data is organized. Could you share the PBIX file with a sample dataset for review?

**Comment by dm-p** [comment] 2024-12-13 02:11
Closing this as it's a potential fix to Vega-Lite. As always, if/when a build emerges that solves the issue, we can update Deneb accordingly.

**Closed by dm-p** 2024-12-13 02:11 UTC
Labels: vega/vega-lite limitation
